config/routes.rb
Rails.application.routes.draw do
  get 'recording_test/new'
  get 'recording_test/create'
  # get '/recording_test/audio_recording_controller.js', to: ''
  devise_for :students, controllers: {
    registrations: 'students'
  }
  devise_for :tutors, controllers: {
    registrations: 'tutors'
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :tutors
  
  resources :students
  
  resources :instruments

  resources :music_sessions

  resources :music_sessions do
    resources :tasks
  end

  resources :music_sessions do
    resources :student_sessions, only: [:new, :create]
  end

  resources :pages
  
  get "dashboard", to: "pages#dashboard"
  # Defines the root path route ("/")
  root "pages#home"
end

app/models/student.rb
# == Schema Information
#
# Table name: students
#
#  id                     :bigint           not null, primary key
#  avatarID               :string
#  coins                  :integer
#  current_sign_in_at     :datetime
#  current_sign_in_ip     :string
#  dayStreak              :integer
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  experience             :string
#  forename               :string
#  last_sign_in_at        :datetime
#  last_sign_in_ip        :string
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  sign_in_count          :integer          default(0), not null
#  studentID              :string
#  surname                :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_students_on_email                 (email) UNIQUE
#  index_students_on_reset_password_token  (reset_password_token) UNIQUE
#
class Student < ApplicationRecord
  def full_name
    "#{forename} #{surname}"
  end
  
  has_many :instruments
  has_many :tutors, through: :instruments
  has_many :avatar_ownership


  has_many :student_sessions
  has_many :music_sessions, through: :student_sessions

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  #need to be changed to use cancancan
  before_action :authenticate_tutor!
  before_action :set_student, only: %i[ show destroy edit update ]

  def index
    if params[:status] == "personal"
      @students = current_tutor.students
    else
      if current_tutor.admin?
        @students = Student.all
      else
        redirect_to dashboard_path, notice: 'you do not have access to that'
        end
    end
  end

  def new
    @student = Student.new
  end

  # POST /products
  def create
    @student = Student.new(student_params.except(:instruments))
    if @student.save
      instrument = current_tutor.instruments.create(instrument: student_params["instruments"]["instrument"], student: @student)
      redirect_to students_path, notice: "student was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @instrument = Instrument.find_by(student_id: @student.id)
    @instrument.destroy if @instrument != nil
    @student.destroy
    if params[:status] == "personal"
      redirect_to 'students?status=personal', notice: "student was successfully destroyed.", status: :see_other
    else
      redirect_to students_path, notice: "student was successfully destroyed.", status: :see_other
    end
  end

  def edit

  end

  def update
    if @student.update(student_params)
      redirect_to students_path, notice: "Student was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end
  
  private
      def set_student
        @student = Student.find(params[:id])
      end

      def student_params
        params.require(:student).permit(:forename, :surname, :email, :password, instruments: [:instrument])
      end

end

app/views/students/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@student) do |f|
  .card-body
    = f.input :forename, wrapper_html: { class: 'mb-3' }
    = f.input :surname, wrapper_html: { class: 'mb-3' }
    = f.input :email, wrapper_html: { class: 'mb-3' }
    = f.input :password, wrapper_html: { class: 'mb-3' }
    = f.simple_fields_for :instruments do |instrument_form|
      = instrument_form.input :instrument, wrapper_html: { class: 'mb-3' }
  .card-footer.d-flex
    %button.btn.btn-primary{ type: 'submit' }
      Save
    = link_to 'Back', students_path, class: 'btn btn-link ms-auto'
    

app/views/students/edit.html.haml
.row.justify-content-center
  .col-sm-8.col-lg-6
    .card
      .card-header Editing Student
      = render 'form'

app/views/students/index.html.haml
.card
  .card-header.d-flex.align-items-center
    %span Listing Students: 
    %span  (#{@students.size} total.)
    = link_to 'New Student', new_student_path, class: 'btn btn-outline-secondary ms-auto'
  
  %table.table
    %thead
      %tr
        %th Forename
        %th Surname
        %th Email
        %th
    %tbody
      - @students.each do |student|
        %tr
          %td= student.forename
          %td= student.surname
          %td= student.email
          %td
            .btn-toolbar.float-end
              = link_to 'Show', student, class: 'btn btn-outline-secondary btn-sm'
              = link_to 'Modify', edit_student_path(student), class: 'btn btn-outline-secondary ms-1 btn-sm'
              = button_to 'Delete', student , method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-outline-danger ms-1 btn-sm'

app/views/students/new.html.haml
.row.justify-content-center
  .col-sm-8.col-lg-6
    .card
      .card-header New Student
      = render 'form'

app/views/students/show.html.haml
.row.justify-content-center
  .col-sm-8.col-lg-6
    .card
      .card-header
        Student details
      .card-body
        %dl.row.mb-0
          %dt.col-md-3 Name:
          %dd.col-md-9= @student.forename + " " + @student.surname
          %dt.col-md-3 Email:
          %dd.col-md-9= @student.email
          
      .card-footer.d-flex
        = link_to 'Back', students_path, class: 'btn btn-link ms-auto'