config/routes.rb
Rails.application.routes.draw do
  get 'recording_test/new'
  get 'recording_test/create'
  # get '/recording_test/audio_recording_controller.js', to: ''
  devise_for :students, controllers: {
    registrations: 'students'
  }
  devise_for :tutors, controllers: {
    registrations: 'tutors'
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :tutors
  
  resources :students
  
  resources :instruments

  resources :music_sessions

  resources :music_sessions do
    resources :tasks
  end

  resources :music_sessions do
    resources :student_sessions, only: [:new, :create]
  end

  resources :pages
  
  get "dashboard", to: "pages#dashboard"
  # Defines the root path route ("/")
  root "pages#home"
end

app/models/music_session.rb
# == Schema Information
#
# Table name: music_sessions
#
#  id          :bigint           not null, primary key
#  description :string
#  due_date    :datetime
#  title       :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  tutor_id    :bigint
#
# Indexes
#
#  index_music_sessions_on_tutor_id  (tutor_id)
#
class MusicSession < ApplicationRecord
  belongs_to :tutor
  
  has_many :student_sessions
  has_many :students, through: :student_sessions
end

app/controllers/music_sessions_controller.rb
class MusicSessionsController < ApplicationController
  before_action :set_session, only: %i[ show destroy edit update ]

  def index
    if tutor_signed_in?
      @sessions = MusicSession.where(tutor_id: current_tutor.id)
      @tasks = Task.all
    elsif student_signed_in?
      @sessions = current_student.music_sessions
      @tasks = Task.all
    end
  end

  def new
    @session = MusicSession.new
  end

  def create
    @session = MusicSession.create(title: session_params["title"], description: session_params["description"], due_date: session_params["due_date"], tutor_id: current_tutor.id)
    puts session_params["due_date"]
    if @session.save
      redirect_to music_sessions_path, notice: "session was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @session.destroy
    redirect_to music_sessions_url, notice: "session was successfully destroyed.", status: :see_other
  end

  def edit

  end

  def update
    if @session.update(session_params)
      redirect_to music_sessions_path, notice: "Session was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def show
    @tasks = Task.where(music_session_id: params[:id])
    @students = @session.students
  end

  private
  def set_session
    @session = MusicSession.find(params[:id])
  end

    def session_params
      params.require(:music_session).permit(:title, :description, :due_date)
    end
end

app/helpers/music_session_helper.rb
module MusicSessionHelper
  def student_completed?(music_session, student_id)
    student_session = StudentSession.find_by(music_session: music_session, student_id: student_id)
    student_session ? student_session.completed : false
  end
end

app/views/music_sessions/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@session) do |f|
  .card-body
    = f.input :title, wrapper_html: { class: 'mb-3' }
    = f.input :description, wrapper_html: { class: 'mb-3' }
    = f.datetime_local_field :due_date, wrapper_html: { class: 'mb-3' }
  .card-footer.d-flex
    %button.btn.btn-primary{ type: 'submit' }
      Save
    = link_to 'Back', music_sessions_path, class: 'btn btn-link ms-auto'
    

app/views/music_sessions/edit.html.haml
.row.justify-content-center
  .col-sm-8.col-lg-6
    .card
      .card-header Editing Session
      = render 'form'

app/views/music_sessions/index.html.haml
.card
  .card-header.d-flex.align-items-center
    %span Listing Sessions: 
    %span  (#{@sessions.size} total.)
    - if tutor_signed_in?
      = link_to 'New Session', new_music_session_path, class: 'btn btn-outline-secondary ms-auto'
  - if tutor_signed_in?
    %table.table
      %thead
        %tr
          %th Session Title
          %th Tutor Name
          %th Due Date
          %th No. Tasks
          %th
      %tbody
        - @sessions.each do |session|
          %tr
            %td= session.title
            %td= session.tutor.forename + " " + session.tutor.surname
            %td= session.due_date
            %td
              - session_tasks = @tasks.where(music_session_id: session.id)
              = session_tasks.size
            %td
              .btn-toolbar.float-end
                = link_to 'Show', session, class: 'btn btn-outline-secondary btn-sm'
                = link_to 'Modify', edit_music_session_path(session), class: 'btn btn-outline-secondary ms-1 btn-sm'
                = link_to 'Delete', session , method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-outline-danger ms-1 btn-sm'
  - elsif student_signed_in?
    %table.table
      %thead
        %tr
          %th Session Title
          %th Tutor Name
          %th Due Date
          %th No. Tasks
          %th
      %tbody
        - @sessions.each do |session|
          %tr
            %td= session.title
            %td= session.tutor.forename + " " + session.tutor.surname
            %td= session.due_date
            %td
              - session_tasks = @tasks.where(music_session_id: session.id)
              = session_tasks.size
            %td
              .btn-toolbar.float-end
                = link_to 'Start Session', '#', class: 'btn btn-outline-secondary btn-sm'

app/views/music_sessions/new.html.haml
.row.justify-content-center
  .col-sm-8.col-lg-6
    .card
      .card-header New Session
      = render 'form'

app/views/music_sessions/show.html.haml
.row.justify-content-center
  .col-sm-8.col-lg-6
    .card
      .card-header
        Session details
      .card-body
        %dl.row.mb-0
          %dt.col-md-3 Title:
          %dd.col-md-9= @session.title
          %dt.col-md-3 Description:
          %dd.col-md-9= @session.description
          %dt.col-md-3 Created By:
          %dd.col-md-9= @session.tutor.forename + " " + @session.tutor.surname
          %dt.col-md-3 Due Date:
          %dd.col-md-9= @session.due_date

        .card-header.d-flex.align-items-center
          %span Listing Tasks: 
          %span  (#{@tasks.size} total.)
          = link_to 'New Task', new_music_session_task_path(@session), class: 'btn btn-outline-secondary ms-auto'

        %table.table
          %thead
            %tr
              %th Task Title
              %th Completion Time
              %th Completion Reward
              %th
          %tbody
            - @tasks.each do |task|
              %tr
                %td= task.title
                %td= task.practice_time
                %td= task.reward


        .card-header.d-flex.align-items-center
          %span Assigned Students: 
          %span  (#{@students.size} total.)
          = link_to 'Assign Session to Students', new_music_session_student_session_path(@session), class: 'btn btn-outline-secondary ms-auto'

        %table.table
          %thead
            %tr
              %th Student Name
              %th Completed
              %th Rating
              %th
          %tbody
            - @students.each do |student|
              %tr
                %td= student.forename + student.surname
                %td= student_completed?(@music_session, student.id)

      .card-footer.d-flex
        = link_to 'Back', music_sessions_path, class: 'btn btn-link ms-auto'