config/routes.rb
Rails.application.routes.draw do
  get 'recording_test/new'
  get 'recording_test/create'
  # get '/recording_test/audio_recording_controller.js', to: ''
  devise_for :students, controllers: {
    registrations: 'students'
  }
  devise_for :tutors, controllers: {
    registrations: 'tutors'
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :tutors
  
  resources :students
  
  resources :instruments

  resources :music_sessions

  resources :music_sessions do
    resources :tasks
  end

  resources :music_sessions do
    resources :student_sessions, only: [:new, :create]
  end

  resources :pages
  
  get "dashboard", to: "pages#dashboard"
  # Defines the root path route ("/")
  root "pages#home"
end

app/views/pages/dashboard.html.haml
.card
  .card-header.d-flex.align-items-center
  - if student_signed_in?
    %span Student Dashboard

    %body
      .btn-toolbar.float-end
        = link_to 'View My Sessions', music_sessions_url, class: 'btn btn-outline-secondary btn-sm'

  - elsif tutor_signed_in?
    %span Tutor Dashboard

    %body
      .btn-toolbar.float-end
        = link_to 'Tutor List', tutors_url, class: 'btn btn-outline-secondary btn-sm'
        -if current_tutor.admin?
          = link_to 'View All Students', students_url, class: 'btn btn-outline-secondary btn-sm'
        = link_to 'View My Students', '/students?status=personal', class: 'btn btn-outline-secondary btn-sm'
        = link_to 'View My Sessions', music_sessions_url, class: 'btn btn-outline-secondary btn-sm'

app/views/pages/home.html.haml
= stylesheet_link_tag 'home', media: 'all'

.header 
    %h1 Welcome to 
    = image_pack_tag 'images/mglogofull.png', alt: 'Logo', class: 'logo-image'
    .caption
        %h2 Practice makes Perfect