config/routes.rb
Rails.application.routes.draw do
  get 'recording_test/new'
  get 'recording_test/create'
  # get '/recording_test/audio_recording_controller.js', to: ''
  devise_for :students, controllers: {
    registrations: 'students'
  }
  devise_for :tutors, controllers: {
    registrations: 'tutors'
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :tutors
  
  resources :students
  
  resources :instruments

  resources :music_sessions

  resources :music_sessions do
    resources :tasks
  end

  resources :music_sessions do
    resources :student_sessions, only: [:new, :create]
  end

  resources :pages
  
  get "dashboard", to: "pages#dashboard"
  # Defines the root path route ("/")
  root "pages#home"
end

app/views/layouts/application.html.haml
!!!
%html{ lang: 'en-GB' }
  %head
    %title MusicGuru

    %meta{ :'http-equiv' => "content-type", content: "text/html; charset=utf-8" }
    %meta{ :'http-equiv' => 'X-UA-Compatible', content: 'IE=edge' }
    %meta{ name: "viewport", content: "width=device-width, initial-scale=1.0, shrink-to-fit=no" }

    - if content_for(:description)
      %meta{ content: content_for(:description), name: 'description' }

    %title= ["MusicGuru", content_for(:title)].compact.join(' - ')

    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_pack_tag 'styles', media: 'all'
    = javascript_pack_tag 'application'

  %body
    %header.navbar.navbar-expand-lg.bg-light.mb-3
      .container-fluid
        = link_to '/', class: 'navbar-brand' do
          = image_pack_tag 'images/mglogo.png', height: 40
        %button.navbar-toggler{ type: :button, data: { bs_toggle: :collapse, bs_target: '#navbar-content' }, aria: { controls: 'navbar-content', expanded: 'false', label: 'Toggle navigation' } }
          %span.navbar-toggler-icon
        #navbar-content.navbar-collapse.collapse
          %nav.navbar-nav
            - if tutor_signed_in? || student_signed_in?
              = link_to '/dashboard', class: 'active nav-link' do
                %i.bi-house-fill
                Dashboard
            - else
              = link_to '/', class: 'active nav-link' do
                %i.bi-house-fill
                Home
            - if tutor_signed_in? || student_signed_in?
              .nav-item
                = button_to destroy_tutor_session_path, method: :delete, class: 'nav-link' do
                  Logout
            - else
              .nav-item
                = link_to '/tutors/sign_in', class: 'nav-link' do
                  Tutor Log in 
              .nav-item
                = link_to '/students/sign_in', class: 'nav-link' do
                  Student Log in

    - if flash.present?
      .container-fluid.flash-messages
        - flash.each do |message_type, message|
          - next unless message_type == 'alert' || message_type == 'notice'
          .alert{ class: "alert-#{ message_type == 'notice' ? 'success' : 'danger' }" }= message

    %main
      .container-fluid
        = yield

    %footer
      .container-fluid
        .d-flex.p-3
          Footer text